### ISSUE TITLE
No templates for CS230

### ISSUE THREAD

**Issue by tyathalae** [shervinea/cheatsheet-translation#102]
Hello there,

Great work with the cheat sheets. I want to contribute to the translations of the CS 230 but I do not see the templates for it.
Can you add them?

Thanks

**Comment by afshinea** [comment]
Hi @tyathalae, thanks for the catch. Absolutely! You can find them [here](https://github.com/shervinea/cheatsheet-translation/blob/master/template/convolutional-neural-networks.md), [here](https://github.com/shervinea/cheatsheet-translation/blob/master/template/recurrent-neural-networks.md) and [here](https://github.com/shervinea/cheatsheet-translation/blob/master/template/deep-learning-tips-and-tricks.md).
