### ISSUE TITLE
[vi]Unsupervised translation

### ISSUE THREAD

**Issue by monsterpooka** [shervinea/cheatsheet-translation#174]
@shervinea I wanna join with Unsupervised Learning Cheatsheet into Vietnamese, could you add in progress label for me? Thank you a lot.

**Comment by shervinea** [comment]
Thank you for your help @monsterpooka! 

To do so, you have to [create a pull request](https://github.com/shervinea/cheatsheet-translation/pulls) with the branch you are working on. You can find more information about this process in the 'Translators' section of the [`README`](https://github.com/shervinea/cheatsheet-translation/blob/master/README.md) file.
