### ISSUE TITLE
Separator errors

### ISSUE THREAD

**Issue by AlexandrParkhomenko** [shervinea/cheatsheet-translation#230]
**75. [E-step: Evaluate the posterior probability q(h) that each data point e came from a particular cluster h as follows:[**,**](https://russian.stackexchange.com/questions/7579/differences-in-punctuation-marks-between-russian-and-english)M-step: Use the posterior probabilities q(h) as cluster specific weights on data points e to determine θ through maximum likelihood.]**

&#10230; [Шаг E: Оценить апостериорную вероятность q(h) того[**,**](https://russian.stackexchange.com/questions/7579/differences-in-punctuation-marks-between-russian-and-english) что каждая точка данных e из определенного кластера h следующим образом:, M-шаг: использовать апостериорные вероятности q(h) в качестве весовых коэффициентов для конкретных кластеров точек данных e[**,**](https://russian.stackexchange.com/questions/7579/differences-in-punctuation-marks-between-russian-and-english) чтобы определить θ через максимальное правдоподобие.]

> A comma in English is required only if the sentence can be misunderstood without it. In Russian, a punctuation mark appears regardless of the length of simple sentences that make up a complex one.
**I paint and she writes. 	Я рисую[**,**](https://russian.stackexchange.com/questions/7579/differences-in-punctuation-marks-between-russian-and-english) а она пишет.**

Maybe it's better to use a different separator in arrays, for example, **a semicolon «;»**?

**Comment by shervinea** [comment]
Thanks @AlexandrParkhomenko for the feedback. You're right that adopting a less used character as a separator convention would have been more appropriate in order to avoid ambiguity when distinguishing array elements. We will make sure to do so in future translation iterations.
