### ISSUE TITLE
Possible typo in Supervised Learning file?

### ISSUE THREAD

**Issue by gabriel19913** [shervinea/cheatsheet-translation#35]
In the item 77 of the supervised learning file is written the following:
`77. Hoeffding inequality ― Let Z1,..,Zm be m iid variables drawn from a Bernoulli distribution of parameter ϕ. Let ˆϕ be their sample mean and γ>0 fixed. We have:`

Is the part `m iid variables` right?

**Comment by shervinea** [comment]
Hi @gabriel19913, I believe so. Closing this issue for now, please feel free to re-open it if needed.
