### ISSUE TITLE
Missing part in supervised learning

### ISSUE THREAD

**Issue by kevingo** [shervinea/cheatsheet-translation#74]
Hi, in the [Adaptive boosting](https://stanford.edu/~shervine/teaching/cs-229/cheatsheet-supervised-learning#tree) part, there is a statement `Known as Adaboost`.

However, this statement is missing from the translation file.

**Comment by shervinea** [comment]
Thanks for your message and for seeing this. Could you please add this statement at the very end of the translation file and fill it as well? Thanks!

**Comment by kevingo** [comment]
@shervinea Sure, Because I am working on the `zh-tw` translation, I will add it to the file and reference back here.
